# Decision tree

In [1]:
import pandas as pd
import numpy as np

from src.util.decision_tree_utils import fill_dataframe_random_bools
from src.models.decision_tree import DecisionTreeBuilder

In [2]:
rng = np.random.default_rng(0)
df = pd.DataFrame(
    columns=[
        "Chest pain",
        "Blood circulation normal",
        "Arterial blockade",
        "Heart attack",
    ]
)

df = fill_dataframe_random_bools(rng, df, 4)
display(df.describe())
display(df.head())

       Chest pain Blood circulation normal Arterial blockade Heart attack
count           4                        4                 4            4
unique          1                        2                 2            2
top          True                    False              True        False
freq            4                        2                 3            3

   Chest pain  Blood circulation normal  Arterial blockade  Heart attack
0        True                     False              False         False
1        True                      True               True          True
2        True                      True               True         False
3        True                     False               True         False

In [3]:
target = "Heart attack"
dtb = DecisionTreeBuilder(target)
dt = dtb.build(df)

In [4]:
patient = {
    "Chest pain": True,
    "Blood circulation normal": True,
    "Arterial blockade": False,
}
patient_series = pd.Series(data=patient, index=patient.keys())
display(patient_series)

Chest pain                   True
Blood circulation normal     True
Arterial blockade           False
dtype: bool

In [5]:
pred = dt.predict(patient_series, target)

Blood circulation normal? True
Chest pain? True
Arterial blockade? False
Prediction => False